### ISSUE TITLE
Order Memento

### ISSUE THREAD

**Issue by Vafdaf12** [Questionable-Engineering-Decisions/Hortrog#20]
Following our previous UML Class Diagram, a Customer holds a reference to all the orders that they made. This violates the intent of supplying a Builder to the customer, which is to hide the product being constructed from the customer. An alternative to this is to make use of a Memento, whereby the customer can be provided with a receipt of what they ordered with some limited information (e.g. the total price of their order)

**Comment by MichaelHorwitz** [comment]
Done. Not a memento
