### ISSUE TITLE
Dynamic Food and Drinks

### ISSUE THREAD

**Issue by Vafdaf12** [Questionable-Engineering-Decisions/Hortrog#4]
The tutors mentioned in the demo on 19 Oct 2023 that our menu items should be dynamic. That is, we shouldn't need to create new class files to represent a new pizza topping, for example.

This will require a slight re-design of the ordering system to describe a generic food item with certain properties that we (the users) can define

**Comment by S3BzA** [comment]
Will revise the class diagrams.

**Comment by 21434809** [comment]
reviewed the class diagram and it is shit basically let's just input a string from a menu database, decorate the order, and get a nice Order JSON string from it with a function Order.getJson();

**Comment by Vafdaf12** [comment]
Me and @21434809 devised a system where orders are a composite that can be decorated with additional modifiers, e.g. grilled vs. fried:

![image](https://github.com/Questionable-Engineering-Decisions/Hortrog/assets/25525445/49ec35f7-5667-4a17-8ab1-541f83d13c03)
