### ISSUE TITLE
Waiter-Customer State

### ISSUE THREAD

**Issue by Vafdaf12** [Questionable-Engineering-Decisions/Hortrog#56]
# Waiting State
- _Waiter_: Customer should attempt to get their meal from the waiter (pull model)
- _Manager_: Happiness goes up slightly and a message is output

If a customer waits too long, they transition into the Karen State

# Ordering State
- _Waiter:_  If they are ready to order, retrieve order builder from waiter and construct order using the menu
- _Manager:_ Request the waiter if they are ready to order, otherwise just output a helpul info message

# Eating State
- _Waiter_: Happiness goes down slightly - IM EATIN HERE!
- _Manager_: Happiness goes up slightly - thanks for caring

# Paying State
- _Waiter:_ Retrieve a bill (or something) from the waiter and pay the bill, and leave a rating
- _Manager:_  Retrieve a bill (or something) from the waiter and pay the bill, and leave a rating

# Karen State
- _Waiter:_ Angrily request to speak to the manager
- _Manager:_ Lodge a complaint with the manager and leave without paying

**Comment by 21434809** [comment]
resolved
